name: Periodic health check

on:
  push:
    branches:
      - master
  # schedule:
  # - cron: '0 * * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://shielded-woodland-56383.herokuapp.com/
