name: Testing stuff

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: joined messages
        env:
          JOINED_MESSAGES: ${{ join(toJson(github.event.commits.*.message), " ... " }}
        run: echo "$JOINED_MESSAGES"
      - name: check for skip
        env:
          CONTAINS_SKIP: ${{ contains($JOINED_MESSAGES, "#skip")}}
        run: echo "$CONTAINS_SKIP"
