name: Testing stuff

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

env:
  COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ' / ') }}
  CONTAINS_SKIP: ${{ contains(env.JOINED_MESSAGES, '#skip') }}
  FULL_IF: ${{ github.event_name == 'push' && !env.SKIP }}


jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commit messages
        run: echo "$COMMIT_MESSAGES"
      - name: check for skip
        run: echo "$CONTAINS_SKIP"
      - name: full if condition
        env:
        run: echo "$FULL_IF"
